[package]
name = "serializeable_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = "2.0.110"
quote = "1.0.42"
proc-macro2 = "1.0.103"
tokio = {version = "1.48.0", features = ["io-util"], optional = true}

[lib]
proc-macro = true

[features]
async = ["dep:tokio"]